#
# APCu configuration
#
# http://php.net/manual/fr/apc.configuration.php
#
apc_enable: "1"
apc_shm_size: "256M"
apc_num_files_hint: 0
apc_user_entries_hint: 0
apc_user_ttl: 360
apc_ttl: 360
apc_gc_ttl: 0
# Set to 1 only if your writes are atomic (rsync ok, cp/tar/vim nok)
apc_file_update_protection: 0
