---

- name: APT | Installed required package to compile phalcon
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=3600
  with_items:
    - php5-dev
    - gcc
    - libpcre3-dev
    - checkinstall

- name: SHELL | Check Phalcon installed
  shell: php -i | grep "Phalcon Version"
  register: phalcon_installed
  ignore_errors: true
  changed_when: false

- name: FILE | Create Phalcon root dir
  file: path={{ phalcon_root_dir }} state=directory mode=0755 owner=root

- name: FILE | Create Phalcon source dir
  file: path={{ phalcon_root_dir }}/v{{ phalcon_version }} state=directory mode=0755 owner=root

- name: GET_URL | Download source
  get_url: url={{ phalcon_url }} dest={{ phalcon_root_dir }}/{{ phalcon_version }}.tar.gz

- name: UNARCHIVE | Uncompress source
  unarchive: copy=no src={{ phalcon_root_dir }}/{{ phalcon_version }}.tar.gz dest={{ phalcon_root_dir }}/v{{ phalcon_version }}

- name: SHELL | phpize phalcon
  command: phpize
  args:
    chdir: "{{ phalcon_build_dir }}"
  when: phalcon_installed|failed or not phalcon_installed.stdout.find('{{phalcon_version}}')

- name: SHELL | ./configure phalcon
  command: ./configure --enable-phalcon
  args:
    chdir: "{{ phalcon_build_dir }}"
  when: phalcon_installed|failed or not phalcon_installed.stdout.find('{{ phalcon_version}}')

- name: SHELL | ./configure phalcon
  command: ./configure --enable-phalcon
  args:
    chdir: "{{ phalcon_build_dir }}"
  when: phalcon_installed|failed or not phalcon_installed.stdout.find('{{ phalcon_version}}')

- name: SHELL | compile phalcon
  command: make
  args:
    chdir: "{{ phalcon_build_dir }}"
  when: phalcon_installed|failed or not phalcon_installed.stdout.find('{{ phalcon_version}}')

- name: SHELL | Install phalcon
  command: checkinstall --install --pkgname php5-phalcon --pkgversion '{{ phalcon_version }}~debianiste.1' -A amd64 --nodoc -y
  args:
    chdir: "{{ phalcon_build_dir }}"
  when: phalcon_installed|failed or not phalcon_installed.stdout.find('{{ phalcon_version}}')
  notify: restart php-fpm

- name: COPY | Create phalcon config
  copy: content="extension=phalcon.so" dest=/etc/php5/mods-available/phalcon.ini owner=root group=root mode=0644

- name: COMMAND | Enable phalcon
  command: php5enmod phalcon creates=/etc/php5/fpm/conf.d/20-phalcon.ini
  notify: restart php-fpm

