---
  - name: APT | Install MariaDB key
    apt_key: keyserver="keyserver.ubuntu.com" id="0xcbcb082a1bb943db" state=present

  - name: APT | Add MariaDB repository
    apt_repository: repo='deb {{ mariadb_repository }} {{ ansible_distribution_release }}  main' state=present

  - name: APT | Add MariaDB (src) repository
    apt_repository: repo='deb-src {{ mariadb_repository }} {{ ansible_distribution_release }}  main' state=present

# Bug: percona-toolkit not in squeeze
  - name: Install MariaDB with few related tools
    apt: update_cache=yes pkg={{ item }} state=latest
    with_items: 
      - mariadb-server
      - mytop
      - percona-toolkit
    
