---

- name: APT_KEY | Install Jenkins key
  apt_key: url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present

- name: APT_REPOSITORY | Add Jenkins repository
  apt_repository: repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present

- name: APT | Install Jenkins
  apt: pkg=jenkins state=latest update_cache=yes cache_valid_time=3600
  register: apt

- name: WAIT_FOR | Wait for jenkins running
  wait_for: port=8080 delay=20
  when: apt.changed

