---

- name: INCLUDE | PHP tools (Wheezy)
  include: php_wheezy.yml
  when: ansible_distribution_release == "wheezy"

- name: INCLUDE | PHP tools (Jessie)
  include: php_wheezy.yml
  when: ansible_distribution_release == "jessie"

- name: INCLUDE | APT related (install)
  include: apt.yml

- name: INCLUDE | Get Jenkins CLI tool
  include: cli.yml

- name: INCLUDE | Install plugins
  include: plugins.yml
