---

- name: APT | Install PHP related packages
  apt: pkg={{ item }} state=latest
  with_items:
    - ant
    - libgettext-ant-tasks-java
    - pdepend
    - php-codesniffer
    - phpcpd
    - phploc
    - phpmd
    - phpunit
