---

- name: INCLUDE | upstream
  include: upstream.yml
  when: elasticsearch_use_upstream

- name: FAIL | if Debian Wheezy-
  fail: msg='EleasticSearch is not available in Debian respository'
  when: not elasticsearch_use_upstream and ansible_distribution_major_version <= 7

- name: APT | Install Elasticsearch
  apt: pkg=elasticsearch update_cache=yes cache_valid_time=3600 state=latest

- name: SERVICE | Ensure Elasticsearch is started and enabled
  service: name=elasticsearch state=started enabled=yes
