jenkins_cli: '{{ jenkins_dir }}/jenkins-cli.jar'
jenkins_update_json: '{{ jenkins_dir }}/updates_jenkins.json'
jenkins_plugins:
  - build-pipeline-plugin
  - checkstyle
  - cloverphp
  - crap4j
  - dry
  - htmlpublisher
  - jdepend
  - plot
  - pmd
  - violations
  - xunit
#apt_default_host: "ftp.fr.debian.org"
