#
# APCu configuration
#
# http://php.net/manual/fr/apc.configuration.php
#
apc_enable: "1"
apc_shm_size: "256M"
apc_num_files_hint: 0
apc_user_entries_hint: 0
apc_user_ttl: 360
apc_ttl: 360
apc_gc_ttl: 0
# Set to 1 only if your writes are atomic (rsync ok, cp/tar/vim nok)
apc_file_update_protection: 0


#
# php.ini
#
php_timezone: 'Europe/Paris'
php_display_errors: 'On'
php_display_startup_errors: 'On'
php_error_reporting: 'E_ALL'

#
# PHP-FPM pools
#
php_fpm_socket: 'unix'
php_fpm_unix_sockets:
  - pool_name: 'default'
    mode: '0660'
    user: 'www-data'
    group: 'www-data'
    file: '/var/run/php5-fpm.sock'
    pm_max_children: 250
    pm_start_servers: 10
    pm_min_spare_servers: 10
    pm_max_spare_servers: 20

# not tested yet
php_fpm_tcp_sockets:
  - pool_name: 'default'
    user: 'www-data'
    group: '{{ ansible_default_ipv4.address }}'
    ip: '1.1.1.1'
    port: 9000
    pm_max_children: 250
    pm_start_servers: 10
    pm_min_spare_servers: 10
    pm_max_spare_servers: 20

