---

# Doc: https://wiki.debian.org/HowTo/ChangeHostname
# TODO : notify other services

- name: HOSTNAME
  hostname: name={{ hostname }}
  notify: restart rsyslog
  register: change_hostname

- name: TEMPLATE | Cleanup /etc/hosts
  template: src=etc/hosts.j2 dest=/etc/hosts
  notify: restart rsyslog

# Don't work on Jessie
#- name: SERVICE | Force hostname.sh start
#  service: name=hostname.sh state=started
#  when: change_hostname.changed

- name: REPLACE | Change old fqdn hostname to new on several files
  replace: dest={{ item }} regexp='\b{{ ansible_fqdn }}\b' replace='{{ hostname }}'
  with_items: hostname_files
  ignore_errors: yes
  when: change_hostname.changed

- name: REPLACE | Change old short hostname to new on several files
  replace: dest={{ item }} regexp='\b{{ ansible_hostname }}\b' replace='{{ hostname | regex_replace('^(\w)\..+$', '\\1') }}'
  with_items: hostname_files
  ignore_errors: yes
  when: change_hostname.changed

# Dangerous...
#- name: SERVICE | Force networking restart
#  service: name=networking state=restarted
#  when: change_hostname.changed


